// bitFlipVersion.h
// - Generated by tools/get_version.sh
// - on 2017-11-02_09:03:21
#define BITFLIP_MAJOR   0
#define BITFLIP_MINOR   9
#define BITFLIP_COMMIT  "c7fbd6a"
#define BITFLIP_VERSION "0.9-c7fbd6a"
#define BITFLIP_DATE    "2017-11-02_09:03:21"
