// bitFlipVersion.h
// - Generated by tools/get_version.sh
// - on 2017-11-08_20:45:49
#define BITFLIP_MAJOR   0
#define BITFLIP_MINOR   9
#define BITFLIP_COMMIT  "2da7e08"
#define BITFLIP_VERSION "0.9-2da7e08"
#define BITFLIP_DATE    "2017-11-08_20:45:49"
