#!/bin/sh
DIR=`dirname $0`
FILE=$DIR/../include/bitFlipVersion.h
COMMIT=`git log -1 --pretty=format:%h`
MAJOR=0
MINOR=9
DATE=`date "+%Y-%m-%d_%H:%M:%S"`
printf "// bitFlipVersion.h\n" > $FILE
printf "// - Generated by %s\n" $0>> $FILE
printf "// - on %s\n" $DATE >>  $FILE
printf "#define BITFLIP_MAJOR   %u\n"             $MAJOR >> $FILE
printf "#define BITFLIP_MINOR   %u\n"             $MINOR >> $FILE
printf "#define BITFLIP_COMMIT  \"%s\"\n"        $COMMIT >> $FILE
printf "#define BITFLIP_VERSION \"%u.%u-%s\"\n" $MAJOR $MINOR $COMMIT >> $FILE
printf "#define BITFLIP_DATE    \"%s\"\n"			$DATE >> $FILE
blue=$(tput setaf 4)
normal=$(tput sgr0)

printf '\e[1;34m%-6s\e[m'  "bitFlipVersion.h"
printf  '\e[1;34m%-6s\e[m'   "           Generated by " $0 ""
printf  "\n"
printf    '\e[1;34m%-6s\e[m' "BITFLIP_MAJOR              "             $MAJOR
printf  "\n"
printf   '\e[1;34m%-6s\e[m' "BITFLIP_MINOR              "             $MINOR
printf  "\n"
printf    '\e[1;34m%-6s\e[m' "BITFLIP_COMMIT             "        $COMMIT
printf  "\n"
printf    '\e[1;34m%-6s\e[m' "BITFLIP_VERSION            " $MAJOR $MINOR $COMMIT
printf  "\n"
printf   '\e[1;34m%-6s\e[m' "BITFLIP_DATE               "			$DATE
printf  "\n\n"